# Generated by Django 3.2.9 on 2021-11-24 01:47

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_dataframe_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataframe',
            name='dataframe',
            field=models.FileField(help_text='Acceptable file formats: *.xlsx, *.xls, *.txt, *.json, *.csv', upload_to='core/', validators=[core.validators.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='dataframe',
            name='name',
            field=models.CharField(help_text='Name of the file ', max_length=500),
        ),
    ]
